-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 15:17:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema angular-test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema angular-test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `angular-test` DEFAULT CHARACTER SET utf8 ;
USE `angular-test` ;

-- -----------------------------------------------------
-- Table `angular-test`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular-test`.`User` ;

CREATE TABLE IF NOT EXISTS `angular-test`.`User` (
  `id` CHAR(36) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `angular-test`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular-test`.`Product` ;

CREATE TABLE IF NOT EXISTS `angular-test`.`Product` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `image_path` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `angular-test`.`Product_Variance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular-test`.`Product_Variance` ;

CREATE TABLE IF NOT EXISTS `angular-test`.`Product_Variance` (
  `id` CHAR(36) NOT NULL,
  `info` VARCHAR(45) NOT NULL,
  `price` DECIMAL(6,0) NOT NULL,
  `Product_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `Product_id`),
  INDEX `fk_Product_Variance_Product_idx` (`Product_id` ASC) VISIBLE,
  UNIQUE INDEX `info_UNIQUE` (`info` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Variance_Product`
    FOREIGN KEY (`Product_id`)
    REFERENCES `angular-test`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
